spring:
  application:
    name: nacos-order # 定义当前服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 指定正在运行的Nacos服务器的位置
  datasource:
    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
dubbo:
  protocol:
    port: -1
    name: dubbo
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false

seata:
  tx-service-group: csmall_group #定义失误的分组，一般是以项目为单位的，方便与其他项目区分
  service:
    vgroup-mapping:
      csmall_group: default # csmall_group分组的配置，default会默认配置Seata
      default: localhost:8091
